services:
  db:
    image: postgres:18
    container_name: aerithDb
    environment:
      POSTGRES_USER: aerith
      POSTGRES_PASSWORD: aerithpw
      POSTGRES_DB: aerith
    ports:
      - "5432:5432"
  app: 
    build: .
    container_name: aerithApi
    ports:
     - "3000:3000"

volumes:
  postgres_data: